from pathlib import Path

### Data provided by LG
# Head directory
#data_dir = Path('/cvhci/temp/zihanchen/data/new_images_1M_group1')
data_dir = Path('/cvhci/temp/zihanchen/data/DACON_SMILES_data/')
train_dir = data_dir / 'train' # training images path
test_dir = '/cvhci/temp/zihanchen/data/DACON_SMILES_data/test/'
train_csv_dir = data_dir / 'train.csv'
# train_modified contains information of the train/validation split in a pickle file format. I saved in pickle just for efficiency
train_pickle_dir = data_dir /'train_modified.pkl'
# Sample submission directory
sample_submission_dir = data_dir /'sample_submission.csv'
#sample_submission_dir = 'sample_submission.csv'




### Data directory generated by us
input_data_dir = data_dir / 'input_data' # output path
base_file_name = 'seed_123_max75smiles'

### seed for train/val split
random_seed = 123

### Reversed_token_file used to map numbers to string. 
reversed_token_map_dir = input_data_dir/ f'REVERSED_TOKENMAP_{base_file_name}.json'

